# This script generates the ingame Patchouli documentation
# The source files for the documentation are in python/docs/src; edit those
# DO NOT edit the files in assets/essentials/patchouli_books*, they are auto-generated by this script based on the source files
# *the exception is for translating entries originally created with version 1 of this script. All future entries will be on version 2 or newer
# There are multiple formats of source files mixed together.
# The old format (version 1) uses txt files- see the comment on GenDocs_v1.py for details.
# The new format (version 2) uses JSON files- see the comment on GenDocs_v2.py for details.

import GenDocs_v1
import GenDocs_v2

def run():
	GenDocs_v1.run()  # txt files
	GenDocs_v2.run()  # JSON files with "format": 2

run()