package com.Da_Technomancer.crossroads.client.TESR;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;

public class ModelGear extends ModelBase{
	// fields
	ModelRenderer cent;
	ModelRenderer BB;
	ModelRenderer AAA;
	ModelRenderer AA;
	ModelRenderer BBB;
	ModelRenderer AAAA;
	ModelRenderer AAAAA;
	ModelRenderer BBBB;
	ModelRenderer BBBBB;
	ModelRenderer edge_main;
	ModelRenderer corner_AA;
	ModelRenderer edge_side;
	ModelRenderer cornerBB;
	ModelRenderer cornerAN;
	ModelRenderer cornerAAA;
	ModelRenderer cornerBBB;
	ModelRenderer corner_AB;
	ModelRenderer corner_BA;
	ModelRenderer corner_BN;

	public ModelGear(){
		textureWidth = 64;
		textureHeight = 32;

		cent = new ModelRenderer(this, 28, 26);
		cent.addBox(0F, 0F, 0F, 14, 2, 4);
		cent.setRotationPoint(-7F, 22F, -2F);
		cent.setTextureSize(64, 32);
		cent.mirror = true;
		// setRotation(cent, 0F, 0F, 0F);
		BB = new ModelRenderer(this, 36, 22);
		BB.addBox(0F, 0F, 0F, 12, 2, 2);
		BB.setRotationPoint(-6F, 22F, 2F);
		BB.setTextureSize(64, 32);
		BB.mirror = true;
		// setRotation(BB, 0F, 0F, 0F);
		AAA = new ModelRenderer(this, 42, 19);
		AAA.addBox(0F, 0F, 0F, 10, 2, 1);
		AAA.setRotationPoint(-5F, 22F, -5F);
		AAA.setTextureSize(64, 32);
		AAA.mirror = true;
		// setRotation(AAA, 0F, 0F, 0F);
		AA = new ModelRenderer(this, 36, 10);
		AA.addBox(0F, 0F, 0F, 12, 2, 2);
		AA.setRotationPoint(-6F, 22F, -4F);
		AA.setTextureSize(64, 32);
		AA.mirror = true;
		// setRotation(AA, 0F, 0F, 0F);
		BBB = new ModelRenderer(this, 42, 7);
		BBB.addBox(0F, 0F, 0F, 10, 2, 1);
		BBB.setRotationPoint(-5F, 22F, 4F);
		BBB.setTextureSize(64, 32);
		BBB.mirror = true;
		// setRotation(BBB, 0F, 0F, 0F);
		AAAA = new ModelRenderer(this, 46, 4);
		AAAA.addBox(0F, 0F, 0F, 8, 2, 1);
		AAAA.setRotationPoint(-4F, 22F, -6F);
		AAAA.setTextureSize(64, 32);
		AAAA.mirror = true;
		// setRotation(AAAA, 0F, 0F, 0F);
		AAAAA = new ModelRenderer(this, 54, 1);
		AAAAA.addBox(0F, 0F, 0F, 4, 2, 1);
		AAAAA.setRotationPoint(-2F, 22F, -7F);
		AAAAA.setTextureSize(64, 32);
		AAAAA.mirror = true;
		// setRotation(AAAAA, 0F, 0F, 0F);
		BBBB = new ModelRenderer(this, 46, 14);
		BBBB.addBox(0F, 0F, 0F, 8, 2, 1);
		BBBB.setRotationPoint(-4F, 22F, 5F);
		BBBB.setTextureSize(64, 32);
		BBBB.mirror = true;
		// setRotation(BBBB, 0F, 0F, 0F);
		BBBBB = new ModelRenderer(this, 36, 14);
		BBBBB.addBox(0F, 0F, 0F, 4, 2, 1);
		BBBBB.setRotationPoint(-2F, 22F, 6F);
		BBBBB.setTextureSize(64, 32);
		BBBBB.mirror = true;
		// setRotation(BBBBB, 0F, 0F, 0F);
		edge_main = new ModelRenderer(this, 0, 19);
		edge_main.addBox(0F, 0F, 0F, 18, 1, 2);
		edge_main.setRotationPoint(-9F, 23F, -1F);
		edge_main.setTextureSize(64, 32);
		edge_main.mirror = true;
		// setRotation(edge_main, 0F, 0F, 0F);
		corner_AA = new ModelRenderer(this, 48, 2);
		corner_AA.addBox(0F, 0F, 0F, 2, 1, 1);
		corner_AA.setRotationPoint(-7F, 23F, 6F);
		corner_AA.setTextureSize(64, 32);
		corner_AA.mirror = true;
		// setRotation(corner_AA, 0F, 0F, 0F);
		edge_side = new ModelRenderer(this, 14, 0);
		edge_side.addBox(0F, 0F, 0F, 2, 1, 18);
		edge_side.setRotationPoint(-1F, 23F, -9F);
		edge_side.setTextureSize(64, 32);
		edge_side.mirror = true;
		// setRotation(edge_side, 0F, 0F, 0F);
		cornerBB = new ModelRenderer(this, 10, 22);
		cornerBB.addBox(0F, 0F, 0F, 12, 1, 1);
		cornerBB.setRotationPoint(-6F, 23F, -5F);
		cornerBB.setTextureSize(64, 32);
		cornerBB.mirror = true;
		// setRotation(cornerBB, 0F, 0F, 0F);
		cornerAN = new ModelRenderer(this, 10, 24);
		cornerAN.addBox(0F, 0F, 0F, 12, 1, 1);
		cornerAN.setRotationPoint(-6F, 23F, 4F);
		cornerAN.setTextureSize(64, 32);
		cornerAN.mirror = true;
		// setRotation(cornerAA, 0F, 0F, 0F);
		cornerAAA = new ModelRenderer(this, 2, 16);
		cornerAAA.addBox(0F, 0F, 0F, 14, 1, 1);
		cornerAAA.setRotationPoint(-7F, 23F, 5F);
		cornerAAA.setTextureSize(64, 32);
		cornerAAA.mirror = true;
		// setRotation(cornerAAA, 0F, 0F, 0F);
		cornerBBB = new ModelRenderer(this, 2, 14);
		cornerBBB.addBox(0F, 0F, 0F, 14, 1, 1);
		cornerBBB.setRotationPoint(-7F, 23F, -6F);
		cornerBBB.setTextureSize(64, 32);
		cornerBBB.mirror = true;
		// setRotation(cornerBBB, 0F, 0F, 0F);
		corner_AB = new ModelRenderer(this, 37, 4);
		corner_AB.addBox(0F, 0F, 0F, 2, 1, 1);
		corner_AB.setRotationPoint(5F, 23F, 6F);
		corner_AB.setTextureSize(64, 32);
		corner_AB.mirror = true;
		// setRotation(corner_AB, 0F, 0F, 0F);
		corner_BA = new ModelRenderer(this, 15, 0);
		corner_BA.addBox(0F, 0F, 0F, 2, 1, 1);
		corner_BA.setRotationPoint(-7F, 23F, -7F);
		corner_BA.setTextureSize(64, 32);
		corner_BA.mirror = true;
		// setRotation(corner_BA, 0F, 0F, 0F);
		corner_BN = new ModelRenderer(this, 2, 0);
		corner_BN.addBox(0F, 0F, 0F, 2, 1, 1);
		corner_BN.setRotationPoint(5F, 23F, -7F);
		corner_BN.setTextureSize(64, 32);
		corner_BN.mirror = true;
		// setRotation(corner_BB, 0F, 0F, 0F);
	}

	public void render(){
		float f = 1F / 16F;
		cent.render(f);
		BB.render(f);
		AAA.render(f);
		AA.render(f);
		BBB.render(f);
		AAAA.render(f);
		AAAAA.render(f);
		BBBB.render(f);
		BBBBB.render(f);
		edge_main.render(f);
		corner_AA.render(f);
		edge_side.render(f);
		corner_BN.render(f);
		cornerAN.render(f);
		cornerAAA.render(f);
		cornerBBB.render(f);
		corner_AB.render(f);
		corner_BA.render(f);
		cornerBB.render(f);
	}

}
